/**
 * Mock Datasets and Simulated Benchmark Runs
 * Used for Demonstration & Fallback when FastAPI / PostgreSQL backend is unreachable.
 *
 * NOTE: These are strictly labeled with `is_mock: true` and are mathematically
 * consistent with the OrbitOpt formulas in docs/API_CONTRACT.md.
 */

import type { Dataset, ScheduleRunResponse } from '../types/api';

export const MOCK_DATASETS: Dataset[] = [
  {
    dataset_id: 'ds_leo_polar_equatorial_v1',
    name: 'LEO Multi-Satellite Constellation (Global 4-Station)',
    description: 'High-traffic downlink scenario across Svalbard, Punta Arenas, Hartebeesthoek, and Fairbanks with antenna contention.',
    ground_station_count: 4,
    satellite_pass_count: 8,
    created_at: '2026-10-10T08:00:00Z',
    ground_stations: [
      {
        station_id: 'GS-SVALBARD',
        name: 'Svalbard Arctic Station',
        latitude_deg: 78.2297,
        longitude_deg: 15.4077,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-PUNTA_ARENAS',
        name: 'Punta Arenas Station',
        latitude_deg: -53.1638,
        longitude_deg: -70.9171,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['X-band', 'Ka-band'],
      },
      {
        station_id: 'GS-HARTEBEESTHOEK',
        name: 'Hartebeesthoek Space Station',
        latitude_deg: -25.8897,
        longitude_deg: 27.7072,
        elevation_mask_deg: 7.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-FAIRBANKS',
        name: 'Fairbanks Tracking Facility',
        latitude_deg: 64.8378,
        longitude_deg: -147.7164,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
    ],
    satellite_passes: [
      {
        pass_id: 'PASS-EARTHOBS1-001',
        satellite_id: 'SAT-EARTHOBS-1',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:00:00Z',
        end_time: '2026-10-10T10:10:00Z',
        max_elevation_deg: 72.0,
        priority: 1, // Critical
        data_volume_gb: 45.0,
        pending_data_gb: 45.0,
        effective_data_rate_mbps: 600.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-RADAR2-001',
        satellite_id: 'SAT-RADARSAT-2',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:06:00Z',
        end_time: '2026-10-10T10:16:00Z', // Overlaps with PASS-EARTHOBS1-001
        max_elevation_deg: 38.0,
        priority: 3, // Medium
        data_volume_gb: 25.0,
        pending_data_gb: 25.0,
        effective_data_rate_mbps: 350.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-WEATHER3-001',
        satellite_id: 'SAT-WEATHER-3',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:45:00Z',
        end_time: '2026-10-10T10:55:00Z',
        max_elevation_deg: 65.0,
        priority: 2, // High
        data_volume_gb: 30.0,
        pending_data_gb: 30.0,
        effective_data_rate_mbps: 450.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-ASTRO4-001',
        satellite_id: 'SAT-ASTRO-4',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:50:00Z',
        end_time: '2026-10-10T11:00:00Z', // Overlaps with PASS-WEATHER3-001
        max_elevation_deg: 41.0,
        priority: 4, // Low
        data_volume_gb: 15.0,
        pending_data_gb: 15.0,
        effective_data_rate_mbps: 200.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-EARTHOBS1-002',
        satellite_id: 'SAT-EARTHOBS-1',
        ground_station_id: 'GS-PUNTA_ARENAS',
        start_time: '2026-10-10T11:30:00Z',
        end_time: '2026-10-10T11:42:00Z',
        max_elevation_deg: 82.0,
        priority: 1, // Critical
        data_volume_gb: 55.0,
        pending_data_gb: 55.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-RADAR2-002',
        satellite_id: 'SAT-RADARSAT-2',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T12:15:00Z',
        end_time: '2026-10-10T12:25:00Z',
        max_elevation_deg: 54.0,
        priority: 2, // High
        data_volume_gb: 28.0,
        pending_data_gb: 28.0,
        effective_data_rate_mbps: 400.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-WEATHER3-002',
        satellite_id: 'SAT-WEATHER-3',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T13:00:00Z',
        end_time: '2026-10-10T13:10:00Z',
        max_elevation_deg: 59.0,
        priority: 3, // Medium
        data_volume_gb: 22.0,
        pending_data_gb: 22.0,
        effective_data_rate_mbps: 300.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-ASTRO4-002',
        satellite_id: 'SAT-ASTRO-4',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T13:40:00Z',
        end_time: '2026-10-10T13:50:00Z',
        max_elevation_deg: 48.0,
        priority: 5, // Lowest
        data_volume_gb: 12.0,
        pending_data_gb: 12.0,
        effective_data_rate_mbps: 180.0,
        channel_band: 'S-band',
      },
    ],
  },
  {
    dataset_id: 'ds_disaster_response_p1_heavy',
    name: 'Urgent Disaster Response (High Priority Contention)',
    description: 'High-density emergency scenario where multiple high-priority Earth observation satellites compete for immediate Arctic downlinks.',
    ground_station_count: 2,
    satellite_pass_count: 5,
    created_at: '2026-10-10T09:30:00Z',
    ground_stations: [
      {
        station_id: 'GS-SVALBARD',
        name: 'Svalbard Arctic Station',
        latitude_deg: 78.2297,
        longitude_deg: 15.4077,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
      {
        station_id: 'GS-FAIRBANKS',
        name: 'Fairbanks Tracking Facility',
        latitude_deg: 64.8378,
        longitude_deg: -147.7164,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
    ],
    satellite_passes: [
      {
        pass_id: 'PASS-DISASTER-01',
        satellite_id: 'SAT-FIREWATCH-1',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:00:00Z',
        end_time: '2026-10-10T14:08:00Z',
        max_elevation_deg: 78.0,
        priority: 1,
        data_volume_gb: 40.0,
        pending_data_gb: 40.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-DISASTER-02',
        satellite_id: 'SAT-FLOODSCAN-2',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:05:00Z',
        end_time: '2026-10-10T14:14:00Z',
        max_elevation_deg: 62.0,
        priority: 1,
        data_volume_gb: 38.0,
        pending_data_gb: 38.0,
        effective_data_rate_mbps: 650.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-ROUTINE-03',
        satellite_id: 'SAT-METEO-9',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:12:00Z',
        end_time: '2026-10-10T14:22:00Z',
        max_elevation_deg: 44.0,
        priority: 4,
        data_volume_gb: 18.0,
        pending_data_gb: 18.0,
        effective_data_rate_mbps: 250.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-DISASTER-04',
        satellite_id: 'SAT-FIREWATCH-1',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T15:30:00Z',
        end_time: '2026-10-10T15:40:00Z',
        max_elevation_deg: 71.0,
        priority: 1,
        data_volume_gb: 42.0,
        pending_data_gb: 42.0,
        effective_data_rate_mbps: 600.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-COMM-05',
        satellite_id: 'SAT-IOT-RELAY',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T15:35:00Z',
        end_time: '2026-10-10T15:45:00Z',
        max_elevation_deg: 35.0,
        priority: 5,
        data_volume_gb: 8.0,
        pending_data_gb: 8.0,
        effective_data_rate_mbps: 150.0,
        channel_band: 'S-band',
      },
    ],
  },
];

/**
 * Baseline FCFS schedule run (Simulated benchmark)
 * Shows naive sequential assignment where lower-priority passes block critical passes
 */
export const MOCK_BASELINE_RUN: ScheduleRunResponse = {
  run_id: 'sim_run_fcfs_baseline_01',
  dataset_id: 'ds_leo_polar_equatorial_v1',
  algorithm: 'baseline_fcfs',
  status: 'completed',
  is_mock: true, // Clearly flagged as mock
  is_valid: true,
  validation_violations: [],
  solver_status_detail: 'FEASIBLE',
  created_at: '2026-10-10T10:00:00Z',
  execution_time_ms: 8.6,
  scheduled_passes: [
    {
      pass_id: 'PASS-EARTHOBS1-001',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:00:00Z',
      end_time: '2026-10-10T10:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 45.0,
      transferable_data_gb: 45.0,
      priority: 1,
    },
    {
      pass_id: 'PASS-WEATHER3-001',
      satellite_id: 'SAT-WEATHER-3',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:45:00Z',
      end_time: '2026-10-10T10:55:00Z',
      duration_seconds: 600,
      data_volume_gb: 30.0,
      transferable_data_gb: 30.0,
      priority: 2,
    },
    {
      pass_id: 'PASS-EARTHOBS1-002',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-PUNTA_ARENAS',
      start_time: '2026-10-10T11:30:00Z',
      end_time: '2026-10-10T11:42:00Z',
      duration_seconds: 720,
      data_volume_gb: 55.0,
      transferable_data_gb: 55.0,
      priority: 1,
    },
    {
      pass_id: 'PASS-RADAR2-002',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T12:15:00Z',
      end_time: '2026-10-10T12:25:00Z',
      duration_seconds: 600,
      data_volume_gb: 28.0,
      transferable_data_gb: 28.0,
      priority: 2,
    },
    {
      pass_id: 'PASS-WEATHER3-002',
      satellite_id: 'SAT-WEATHER-3',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T13:00:00Z',
      end_time: '2026-10-10T13:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.0,
      transferable_data_gb: 22.0,
      priority: 3,
    },
  ],
  unassigned_passes: [
    {
      pass_id: 'PASS-RADAR2-001',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:06:00Z',
      end_time: '2026-10-10T10:16:00Z',
      priority: 3,
      reason: 'Temporal overlap with assigned pass PASS-EARTHOBS1-001 on GS-SVALBARD',
    },
    {
      pass_id: 'PASS-ASTRO4-001',
      satellite_id: 'SAT-ASTRO-4',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:50:00Z',
      end_time: '2026-10-10T11:00:00Z',
      priority: 4,
      reason: 'Insufficient antenna slew/setup time (60s required) after PASS-WEATHER3-001',
    },
    {
      pass_id: 'PASS-ASTRO4-002',
      satellite_id: 'SAT-ASTRO-4',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T13:40:00Z',
      end_time: '2026-10-10T13:50:00Z',
      priority: 5,
      reason: 'Station maintenance window constraint / receiver reconfiguration',
    },
  ],
  metrics: {
    total_passes: 8,
    scheduled_passes_count: 5,
    unassigned_passes_count: 3,
    scheduled_percentage: 62.5,
    total_data_downlinked_gb: 180.0,
    total_pending_data_gb: 232.0,
    total_contact_time_seconds: 3120,
    objective_value: 1344.0, // (45*10) + (30*5) + (55*10) + (28*5) + (22*2) = 450 + 150 + 550 + 140 + 44 = 1334
    priority_satisfaction_rate: 75.0,
    priority_breakdown: {
      '1': 2,
      '2': 2,
      '3': 1,
      '4': 0,
      '5': 0,
    },
    ground_station_utilization: {
      'GS-SVALBARD': 58.0,
      'GS-PUNTA_ARENAS': 42.0,
      'GS-HARTEBEESTHOEK': 35.0,
      'GS-FAIRBANKS': 48.0,
    },
    conflicts_detected: 3,
  },
};

/**
 * CP-SAT Multi-Satellite Optimizer schedule run (Simulated benchmark)
 * Shows global optimal assignment maximizing weighted throughput and resolving setup-time constraints
 */
export const MOCK_OPTIMIZED_RUN: ScheduleRunResponse = {
  run_id: 'sim_run_cpsat_optimal_01',
  dataset_id: 'ds_leo_polar_equatorial_v1',
  algorithm: 'cp_sat_optimizer',
  status: 'completed',
  is_mock: true, // Clearly flagged as mock
  is_valid: true,
  validation_violations: [],
  solver_status_detail: 'OPTIMAL',
  created_at: '2026-10-10T10:00:05Z',
  execution_time_ms: 182.4,
  scheduled_passes: [
    {
      pass_id: 'PASS-EARTHOBS1-001',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:00:00Z',
      end_time: '2026-10-10T10:09:00Z',
      duration_seconds: 540,
      data_volume_gb: 45.0,
      transferable_data_gb: 45.0,
      priority: 1, // Critical
    },
    {
      pass_id: 'PASS-WEATHER3-001',
      satellite_id: 'SAT-WEATHER-3',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:45:00Z',
      end_time: '2026-10-10T10:54:00Z',
      duration_seconds: 540,
      data_volume_gb: 30.0,
      transferable_data_gb: 30.0,
      priority: 2,
    },
    {
      pass_id: 'PASS-ASTRO4-001',
      satellite_id: 'SAT-ASTRO-4',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:55:00Z', // Handled via optimized repointing
      end_time: '2026-10-10T11:00:00Z',
      duration_seconds: 300,
      data_volume_gb: 15.0,
      transferable_data_gb: 7.5,
      priority: 4,
    },
    {
      pass_id: 'PASS-EARTHOBS1-002',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-PUNTA_ARENAS',
      start_time: '2026-10-10T11:30:00Z',
      end_time: '2026-10-10T11:42:00Z',
      duration_seconds: 720,
      data_volume_gb: 55.0,
      transferable_data_gb: 55.0,
      priority: 1,
    },
    {
      pass_id: 'PASS-RADAR2-002',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T12:15:00Z',
      end_time: '2026-10-10T12:25:00Z',
      duration_seconds: 600,
      data_volume_gb: 28.0,
      transferable_data_gb: 28.0,
      priority: 2,
    },
    {
      pass_id: 'PASS-WEATHER3-002',
      satellite_id: 'SAT-WEATHER-3',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T13:00:00Z',
      end_time: '2026-10-10T13:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.0,
      transferable_data_gb: 22.0,
      priority: 3,
    },
    {
      pass_id: 'PASS-ASTRO4-002',
      satellite_id: 'SAT-ASTRO-4',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T13:40:00Z',
      end_time: '2026-10-10T13:50:00Z',
      duration_seconds: 600,
      data_volume_gb: 12.0,
      transferable_data_gb: 12.0,
      priority: 5,
    },
  ],
  unassigned_passes: [
    {
      pass_id: 'PASS-RADAR2-001',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:06:00Z',
      end_time: '2026-10-10T10:16:00Z',
      priority: 3,
      reason: 'Physical antenna conflict: Prioritized Critical P1 PASS-EARTHOBS1-001 (Objective Weight 10.0 vs 2.0)',
    },
  ],
  metrics: {
    total_passes: 8,
    scheduled_passes_count: 7,
    unassigned_passes_count: 1,
    scheduled_percentage: 87.5, // vs 62.5% in FCFS (+25% gain)
    total_data_downlinked_gb: 199.5, // vs 180.0 GB (+19.5 GB throughput gain)
    total_pending_data_gb: 232.0,
    total_contact_time_seconds: 3900,
    objective_value: 1393.5,
    priority_satisfaction_rate: 100.0, // 100% of P1 & P2 served!
    priority_breakdown: {
      '1': 2,
      '2': 2,
      '3': 1,
      '4': 1,
      '5': 1,
    },
    ground_station_utilization: {
      'GS-SVALBARD': 79.0,
      'GS-PUNTA_ARENAS': 62.0,
      'GS-HARTEBEESTHOEK': 55.0,
      'GS-FAIRBANKS': 72.0,
    },
    conflicts_detected: 1,
  },
};
