/**
 * Mock Datasets and Simulated Benchmark Runs
 * Used for Demonstration & Fallback when FastAPI / PostgreSQL backend is unreachable.
 *
 * NOTE: These are strictly labeled with `is_mock: true` and are mathematically
 * consistent with the OrbitOpt formulas in docs/API_CONTRACT.md.
 */

import type { Dataset, ScheduleRunResponse } from '../types/api';

export const MOCK_DATASETS: Dataset[] = [
  {
    dataset_id: 'ds_priority_contention_benchmark',
    name: 'Priority Contention Benchmark (Global 4-Station)',
    description: 'High-contention downlink scenario where earlier low-priority passes conflict with later critical passes on Svalbard & Fairbanks antennas, proving CP-SAT optimization gain.',
    ground_station_count: 4,
    satellite_pass_count: 8,
    created_at: '2026-10-10T08:00:00Z',
    ground_stations: [
      {
        station_id: 'GS-SVALBARD',
        name: 'Svalbard Arctic Station',
        latitude_deg: 78.2297,
        longitude_deg: 15.4077,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-PUNTA_ARENAS',
        name: 'Punta Arenas Station',
        latitude_deg: -53.1638,
        longitude_deg: -70.9171,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['X-band', 'Ka-band'],
      },
      {
        station_id: 'GS-HARTEBEESTHOEK',
        name: 'Hartebeesthoek Space Station',
        latitude_deg: -25.8897,
        longitude_deg: 27.7072,
        elevation_mask_deg: 7.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-FAIRBANKS',
        name: 'Fairbanks Tracking Facility',
        latitude_deg: 64.8378,
        longitude_deg: -147.7164,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
    ],
    satellite_passes: [
      {
        pass_id: 'PASS-RADAR-001',
        satellite_id: 'SAT-RADARSAT-1',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:00:00Z',
        end_time: '2026-10-10T10:10:00Z',
        max_elevation_deg: 38.0,
        priority: 3, // Medium (arrives earlier than critical pass)
        data_volume_gb: 25.0,
        pending_data_gb: 25.0,
        effective_data_rate_mbps: 350.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-EARTHOBS-001',
        satellite_id: 'SAT-EARTHOBS-1',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:04:00Z',
        end_time: '2026-10-10T10:14:00Z', // Overlaps with PASS-RADAR-001
        max_elevation_deg: 72.0,
        priority: 1, // Critical
        data_volume_gb: 45.0,
        pending_data_gb: 45.0,
        effective_data_rate_mbps: 600.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-ASTRO-001',
        satellite_id: 'SAT-ASTRO-1',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:45:00Z',
        end_time: '2026-10-10T10:55:00Z',
        max_elevation_deg: 41.0,
        priority: 4, // Low (arrives earlier than high-priority pass)
        data_volume_gb: 15.0,
        pending_data_gb: 15.0,
        effective_data_rate_mbps: 200.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-WEATHER-001',
        satellite_id: 'SAT-WEATHER-1',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:48:00Z',
        end_time: '2026-10-10T10:58:00Z', // Overlaps with PASS-ASTRO-001
        max_elevation_deg: 65.0,
        priority: 2, // High
        data_volume_gb: 30.0,
        pending_data_gb: 30.0,
        effective_data_rate_mbps: 450.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-EARTHOBS-002',
        satellite_id: 'SAT-EARTHOBS-2',
        ground_station_id: 'GS-PUNTA_ARENAS',
        start_time: '2026-10-10T11:30:00Z',
        end_time: '2026-10-10T11:42:00Z',
        max_elevation_deg: 82.0,
        priority: 1, // Critical
        data_volume_gb: 55.0,
        pending_data_gb: 55.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-RADAR-002',
        satellite_id: 'SAT-RADARSAT-2',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T12:15:00Z',
        end_time: '2026-10-10T12:25:00Z',
        max_elevation_deg: 54.0,
        priority: 2, // High
        data_volume_gb: 28.0,
        pending_data_gb: 28.0,
        effective_data_rate_mbps: 400.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-WEATHER-002',
        satellite_id: 'SAT-WEATHER-2',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T13:00:00Z',
        end_time: '2026-10-10T13:10:00Z',
        max_elevation_deg: 59.0,
        priority: 3, // Medium
        data_volume_gb: 22.0,
        pending_data_gb: 22.0,
        effective_data_rate_mbps: 300.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-ASTRO-002',
        satellite_id: 'SAT-ASTRO-2',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T13:40:00Z',
        end_time: '2026-10-10T13:50:00Z',
        max_elevation_deg: 48.0,
        priority: 5, // Lowest
        data_volume_gb: 12.0,
        pending_data_gb: 12.0,
        effective_data_rate_mbps: 180.0,
        channel_band: 'S-band',
      },
    ],
  },
  {
    dataset_id: 'ds_leo_constellation_baseline',
    name: 'LEO Multi-Satellite Constellation (High Contention)',
    description: 'Multi-satellite constellation scenario with antenna scheduling conflicts where CP-SAT maximizes total payload downlink over naive FCFS.',
    ground_station_count: 4,
    satellite_pass_count: 8,
    created_at: '2026-10-10T08:00:00Z',
    ground_stations: [
      {
        station_id: 'GS-SVALBARD',
        name: 'Svalbard Arctic Station',
        latitude_deg: 78.2297,
        longitude_deg: 15.4077,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-PUNTA_ARENAS',
        name: 'Punta Arenas Station',
        latitude_deg: -53.1638,
        longitude_deg: -70.9171,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['X-band', 'Ka-band'],
      },
      {
        station_id: 'GS-HARTEBEESTHOEK',
        name: 'Hartebeesthoek Space Station',
        latitude_deg: -25.8897,
        longitude_deg: 27.7072,
        elevation_mask_deg: 7.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band'],
      },
      {
        station_id: 'GS-FAIRBANKS',
        name: 'Fairbanks Tracking Facility',
        latitude_deg: 64.8378,
        longitude_deg: -147.7164,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
    ],
    satellite_passes: [
      {
        pass_id: 'PASS-LEO-ROUTINE-01',
        satellite_id: 'SAT-LEO-ROUTINE',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:00:00Z',
        end_time: '2026-10-10T10:09:00Z',
        max_elevation_deg: 35.0,
        priority: 4,
        data_volume_gb: 12.0,
        pending_data_gb: 12.0,
        effective_data_rate_mbps: 200.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-LEO-OPTICAL-02',
        satellite_id: 'SAT-LEO-OPTICAL',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T10:03:00Z',
        end_time: '2026-10-10T10:13:00Z',
        max_elevation_deg: 74.0,
        priority: 1,
        data_volume_gb: 48.0,
        pending_data_gb: 48.0,
        effective_data_rate_mbps: 650.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-LEO-BEACON-03',
        satellite_id: 'SAT-LEO-BEACON',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:40:00Z',
        end_time: '2026-10-10T10:50:00Z',
        max_elevation_deg: 38.0,
        priority: 5,
        data_volume_gb: 10.0,
        pending_data_gb: 10.0,
        effective_data_rate_mbps: 150.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-LEO-SAR-04',
        satellite_id: 'SAT-LEO-SAR',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T10:43:00Z',
        end_time: '2026-10-10T10:54:00Z',
        max_elevation_deg: 68.0,
        priority: 2,
        data_volume_gb: 35.0,
        pending_data_gb: 35.0,
        effective_data_rate_mbps: 500.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-LEO-HYPERSPEC-05',
        satellite_id: 'SAT-LEO-HYPERSPEC',
        ground_station_id: 'GS-PUNTA_ARENAS',
        start_time: '2026-10-10T11:15:00Z',
        end_time: '2026-10-10T11:27:00Z',
        max_elevation_deg: 80.0,
        priority: 1,
        data_volume_gb: 52.0,
        pending_data_gb: 52.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-LEO-CLIMATE-06',
        satellite_id: 'SAT-LEO-CLIMATE',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T12:00:00Z',
        end_time: '2026-10-10T12:10:00Z',
        max_elevation_deg: 58.0,
        priority: 2,
        data_volume_gb: 30.0,
        pending_data_gb: 30.0,
        effective_data_rate_mbps: 400.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-LEO-OCEAN-07',
        satellite_id: 'SAT-LEO-OCEAN',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T12:50:00Z',
        end_time: '2026-10-10T13:00:00Z',
        max_elevation_deg: 52.0,
        priority: 3,
        data_volume_gb: 20.0,
        pending_data_gb: 20.0,
        effective_data_rate_mbps: 280.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-LEO-MAG-08',
        satellite_id: 'SAT-LEO-MAG',
        ground_station_id: 'GS-HARTEBEESTHOEK',
        start_time: '2026-10-10T13:30:00Z',
        end_time: '2026-10-10T13:40:00Z',
        max_elevation_deg: 45.0,
        priority: 4,
        data_volume_gb: 14.0,
        pending_data_gb: 14.0,
        effective_data_rate_mbps: 180.0,
        channel_band: 'S-band',
      },
    ],
  },
  {
    dataset_id: 'ds_disaster_response_p1_heavy',
    name: 'Urgent Disaster Response (High Priority Contention)',
    description: 'Emergency scenario where multiple high-priority Earth observation satellites compete for Arctic downlinks, proving CP-SAT prioritization.',
    ground_station_count: 2,
    satellite_pass_count: 6,
    created_at: '2026-10-10T09:30:00Z',
    ground_stations: [
      {
        station_id: 'GS-SVALBARD',
        name: 'Svalbard Arctic Station',
        latitude_deg: 78.2297,
        longitude_deg: 15.4077,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
      {
        station_id: 'GS-FAIRBANKS',
        name: 'Fairbanks Tracking Facility',
        latitude_deg: 64.8378,
        longitude_deg: -147.7164,
        elevation_mask_deg: 5.0,
        max_concurrent_passes: 1,
        supported_bands: ['S-band', 'X-band', 'Ka-band'],
      },
    ],
    satellite_passes: [
      {
        pass_id: 'PASS-IOT-BEACON-01',
        satellite_id: 'SAT-IOT-BEACON',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:00:00Z',
        end_time: '2026-10-10T14:08:00Z',
        max_elevation_deg: 34.0,
        priority: 5,
        data_volume_gb: 8.0,
        pending_data_gb: 8.0,
        effective_data_rate_mbps: 150.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-DISASTER-FIRE-02',
        satellite_id: 'SAT-FIREWATCH-1',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:03:00Z',
        end_time: '2026-10-10T14:12:00Z',
        max_elevation_deg: 78.0,
        priority: 1,
        data_volume_gb: 45.0,
        pending_data_gb: 45.0,
        effective_data_rate_mbps: 750.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-DISASTER-FLOOD-03',
        satellite_id: 'SAT-FLOODSCAN-2',
        ground_station_id: 'GS-SVALBARD',
        start_time: '2026-10-10T14:18:00Z',
        end_time: '2026-10-10T14:28:00Z',
        max_elevation_deg: 65.0,
        priority: 1,
        data_volume_gb: 42.0,
        pending_data_gb: 42.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'X-band',
      },
      {
        pass_id: 'PASS-ROUTINE-METEO-04',
        satellite_id: 'SAT-METEO-9',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T15:20:00Z',
        end_time: '2026-10-10T15:30:00Z',
        max_elevation_deg: 42.0,
        priority: 4,
        data_volume_gb: 14.0,
        pending_data_gb: 14.0,
        effective_data_rate_mbps: 220.0,
        channel_band: 'S-band',
      },
      {
        pass_id: 'PASS-DISASTER-QUAKE-05',
        satellite_id: 'SAT-QUAKESCAN-3',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T15:24:00Z',
        end_time: '2026-10-10T15:35:00Z',
        max_elevation_deg: 72.0,
        priority: 1,
        data_volume_gb: 46.0,
        pending_data_gb: 46.0,
        effective_data_rate_mbps: 700.0,
        channel_band: 'Ka-band',
      },
      {
        pass_id: 'PASS-DISASTER-SAR-06',
        satellite_id: 'SAT-RADARSAT-3',
        ground_station_id: 'GS-FAIRBANKS',
        start_time: '2026-10-10T15:40:00Z',
        end_time: '2026-10-10T15:50:00Z',
        max_elevation_deg: 58.0,
        priority: 2,
        data_volume_gb: 32.0,
        pending_data_gb: 32.0,
        effective_data_rate_mbps: 450.0,
        channel_band: 'X-band',
      },
    ],
  },
];

/**
 * Baseline FCFS schedule run (Simulated benchmark)
 * Shows naive sequential assignment where lower-priority passes block critical passes
 */
export const MOCK_BASELINE_RUN: ScheduleRunResponse = {
  run_id: 'sim_run_fcfs_baseline_01',
  dataset_id: 'ds_priority_contention_benchmark',
  algorithm: 'baseline_fcfs',
  status: 'completed',
  is_mock: true, // Clearly flagged as mock
  is_valid: true,
  validation_violations: [],
  solver_status_detail: 'FEASIBLE',
  created_at: '2026-10-10T10:00:00Z',
  execution_time_ms: 8.6,
  scheduled_passes: [
    {
      pass_id: 'PASS-RADAR-001',
      satellite_id: 'SAT-RADARSAT-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:00:00Z',
      end_time: '2026-10-10T10:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.5,
      transferable_data_gb: 22.5,
      priority: 3,
    },
    {
      pass_id: 'PASS-ASTRO-001',
      satellite_id: 'SAT-ASTRO-1',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:45:00Z',
      end_time: '2026-10-10T10:55:00Z',
      duration_seconds: 600,
      data_volume_gb: 15.0,
      transferable_data_gb: 15.0,
      priority: 4,
    },
    {
      pass_id: 'PASS-EARTHOBS-002',
      satellite_id: 'SAT-EARTHOBS-2',
      ground_station_id: 'GS-PUNTA_ARENAS',
      start_time: '2026-10-10T11:30:00Z',
      end_time: '2026-10-10T11:42:00Z',
      duration_seconds: 720,
      data_volume_gb: 55.0,
      transferable_data_gb: 55.0,
      priority: 1,
    },
    {
      pass_id: 'PASS-RADAR-002',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T12:15:00Z',
      end_time: '2026-10-10T12:25:00Z',
      duration_seconds: 600,
      data_volume_gb: 13.5,
      transferable_data_gb: 13.5,
      priority: 2,
    },
    {
      pass_id: 'PASS-WEATHER-002',
      satellite_id: 'SAT-WEATHER-2',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T13:00:00Z',
      end_time: '2026-10-10T13:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.0,
      transferable_data_gb: 22.0,
      priority: 3,
    },
    {
      pass_id: 'PASS-ASTRO-002',
      satellite_id: 'SAT-ASTRO-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T13:40:00Z',
      end_time: '2026-10-10T13:50:00Z',
      duration_seconds: 600,
      data_volume_gb: 12.0,
      transferable_data_gb: 12.0,
      priority: 5,
    },
  ],
  unassigned_passes: [
    {
      pass_id: 'PASS-EARTHOBS-001',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:04:00Z',
      end_time: '2026-10-10T10:14:00Z',
      priority: 1,
      reason: 'Naive FCFS dropped Critical P1 pass because earlier arriving Medium P3 pass locked GS-SVALBARD',
    },
    {
      pass_id: 'PASS-WEATHER-001',
      satellite_id: 'SAT-WEATHER-1',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:48:00Z',
      end_time: '2026-10-10T10:58:00Z',
      priority: 2,
      reason: 'Naive FCFS dropped High P2 pass because earlier Low P4 pass locked GS-FAIRBANKS',
    },
  ],
  metrics: {
    total_passes: 8,
    scheduled_passes_count: 6,
    unassigned_passes_count: 2,
    scheduled_percentage: 75.0,
    total_data_downlinked_gb: 140.0,
    total_pending_data_gb: 232.0,
    total_contact_time_seconds: 3720,
    objective_value: 727.5,
    priority_satisfaction_rate: 51.78,
    priority_breakdown: {
      '1': 1,
      '2': 1,
      '3': 2,
      '4': 1,
      '5': 1,
    },
    ground_station_utilization: {
      'GS-SVALBARD': 25.0,
      'GS-PUNTA_ARENAS': 12.5,
      'GS-HARTEBEESTHOEK': 25.0,
      'GS-FAIRBANKS': 12.5,
    },
    conflicts_detected: 2,
  },
};

/**
 * CP-SAT Multi-Satellite Optimizer schedule run (Simulated benchmark)
 * Shows global optimal assignment maximizing weighted throughput and resolving setup-time constraints
 */
export const MOCK_OPTIMIZED_RUN: ScheduleRunResponse = {
  run_id: 'sim_run_cpsat_optimal_01',
  dataset_id: 'ds_priority_contention_benchmark',
  algorithm: 'cp_sat_optimizer',
  status: 'completed',
  is_mock: true, // Clearly flagged as mock
  is_valid: true,
  validation_violations: [],
  solver_status_detail: 'OPTIMAL',
  created_at: '2026-10-10T10:00:05Z',
  execution_time_ms: 182.4,
  scheduled_passes: [
    {
      pass_id: 'PASS-EARTHOBS-001',
      satellite_id: 'SAT-EARTHOBS-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:04:00Z',
      end_time: '2026-10-10T10:14:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.5,
      transferable_data_gb: 22.5,
      priority: 1, // Critical prioritized over P3
    },
    {
      pass_id: 'PASS-WEATHER-001',
      satellite_id: 'SAT-WEATHER-1',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:48:00Z',
      end_time: '2026-10-10T10:58:00Z',
      duration_seconds: 600,
      data_volume_gb: 30.0,
      transferable_data_gb: 30.0,
      priority: 2, // High prioritized over P4
    },
    {
      pass_id: 'PASS-EARTHOBS-002',
      satellite_id: 'SAT-EARTHOBS-2',
      ground_station_id: 'GS-PUNTA_ARENAS',
      start_time: '2026-10-10T11:30:00Z',
      end_time: '2026-10-10T11:42:00Z',
      duration_seconds: 720,
      data_volume_gb: 55.0,
      transferable_data_gb: 55.0,
      priority: 1,
    },
    {
      pass_id: 'PASS-RADAR-002',
      satellite_id: 'SAT-RADARSAT-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T12:15:00Z',
      end_time: '2026-10-10T12:25:00Z',
      duration_seconds: 600,
      data_volume_gb: 13.5,
      transferable_data_gb: 13.5,
      priority: 2,
    },
    {
      pass_id: 'PASS-WEATHER-002',
      satellite_id: 'SAT-WEATHER-2',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T13:00:00Z',
      end_time: '2026-10-10T13:10:00Z',
      duration_seconds: 600,
      data_volume_gb: 22.0,
      transferable_data_gb: 22.0,
      priority: 3,
    },
    {
      pass_id: 'PASS-ASTRO-002',
      satellite_id: 'SAT-ASTRO-2',
      ground_station_id: 'GS-HARTEBEESTHOEK',
      start_time: '2026-10-10T13:40:00Z',
      end_time: '2026-10-10T13:50:00Z',
      duration_seconds: 600,
      data_volume_gb: 12.0,
      transferable_data_gb: 12.0,
      priority: 5,
    },
  ],
  unassigned_passes: [
    {
      pass_id: 'PASS-RADAR-001',
      satellite_id: 'SAT-RADARSAT-1',
      ground_station_id: 'GS-SVALBARD',
      start_time: '2026-10-10T10:00:00Z',
      end_time: '2026-10-10T10:10:00Z',
      priority: 3,
      reason: 'Dropped by CP-SAT in favor of higher priority critical pass PASS-EARTHOBS-001 on GS-SVALBARD',
    },
    {
      pass_id: 'PASS-ASTRO-001',
      satellite_id: 'SAT-ASTRO-1',
      ground_station_id: 'GS-FAIRBANKS',
      start_time: '2026-10-10T10:45:00Z',
      end_time: '2026-10-10T10:55:00Z',
      priority: 4,
      reason: 'Dropped by CP-SAT in favor of higher priority high pass PASS-WEATHER-001 on GS-FAIRBANKS',
    },
  ],
  metrics: {
    total_passes: 8,
    scheduled_passes_count: 6,
    unassigned_passes_count: 2,
    scheduled_percentage: 75.0,
    total_data_downlinked_gb: 155.0,
    total_pending_data_gb: 232.0,
    total_contact_time_seconds: 3720,
    objective_value: 1042.5,
    priority_satisfaction_rate: 74.2,
    priority_breakdown: {
      '1': 2,
      '2': 2,
      '3': 1,
      '4': 0,
      '5': 1,
    },
    ground_station_utilization: {
      'GS-SVALBARD': 25.0,
      'GS-PUNTA_ARENAS': 12.5,
      'GS-HARTEBEESTHOEK': 25.0,
      'GS-FAIRBANKS': 12.5,
    },
    conflicts_detected: 2,
  },
};
